### ISSUE TITLE
[Modification] Modify Home page

### ISSUE THREAD

**Issue by dravadhis** [CoLDorg/COLD#3]
The current website is just a basic front-end skeleton. As such some changes need to be made on the home page.

<h2>Tasks</h2>

- [x] Change logo to coldorg logo.
- [x] Change background image on the first page of the home page. The background should take the visibility of the logo into consideration.
- [x] The Home page displays a flickering message 'Hi We are COLD -> Hi we are Developers'. This needs to be changed to 'Co.L.D.->Code.Learn.Discuss.
- [x] 'Contact us' button label should be changed to 'Join Us' and should link to the membership form.
- [x] 'Download work' should be changed to 'Our Projects' and should link to the Projects page.
- [x] In the About section the logo should be changed to the organisation logo.
- [x] In the Services section, the services mentioned should be the ones mentioned in the 'Summary and timeline.docx' document.
- [x] The 'Mentors and Members' section should have title 'Core Committee'. The member cards need to be modified to include image,name, post, description(not neccessary), github profile link (if exists), linkedin profile link (if exists).
- [x] The 'Works' section should display some of the club's projects.
- [x] A new section titled 'Join Us' should be added. It should contain a the title, a small piece of text like "Interested in being a part of Cold?" and a button which leads to the membership form.
- [x] Add constitution button on the homepage.

<h2> Resources </h2>
Resources like logo, proposal letter, constitutuiton document, etc. can be found here:<br>
https://drive.google.com/drive/folders/1gGkKoIPEiqJQu7H2FEy80SaUi6qK3Ac8?usp=sharing

<h2> Guidelines </h2>

1. Create a specific issue for each task you pick up. Tasks of similar nature can be grouped into one issue. After the work on some task is completed, check mark the task here.  
2. Please comment here when you take up a task from this list. Mention the issue you open when taking up a task.
3. New tasks related to the home page can be added here. Just edit this comment to add a new task.

**Comment by AmaaniGoose** [comment]
Added required modifications except the second and the third last ones
